# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/qualityOfLifeMS.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/qualityOfLifeMS.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprotos/qualityOfLifeMS.proto\"\x1c\n\x07rankreq\x12\x11\n\tlocations\x18\x01 \x02(\t\"-\n\x07ranking\x12\x10\n\x08rankings\x18\x01 \x02(\t\x12\x10\n\x08response\x18\x02 \x02(\t2s\n\x0fqualityOfLifeMS\x12\x1e\n\x06getEnv\x12\x08.rankreq\x1a\x08.ranking\"\x00\x12\x1f\n\x07getWalk\x12\x08.rankreq\x1a\x08.ranking\"\x00\x12\x1f\n\x07getBoth\x12\x08.rankreq\x1a\x08.ranking\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.qualityOfLifeMS_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RANKREQ']._serialized_start=32
  _globals['_RANKREQ']._serialized_end=60
  _globals['_RANKING']._serialized_start=62
  _globals['_RANKING']._serialized_end=107
  _globals['_QUALITYOFLIFEMS']._serialized_start=109
  _globals['_QUALITYOFLIFEMS']._serialized_end=224
# @@protoc_insertion_point(module_scope)
