# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import siteSelectionMS_pb2 as protos_dot_siteSelectionMS__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/siteSelectionMS_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class siteSelectionMSStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getCommute = channel.unary_unary(
                '/proxPackage.siteSelectionMS/getCommute',
                request_serializer=protos_dot_siteSelectionMS__pb2.rankProxRequest.SerializeToString,
                response_deserializer=protos_dot_siteSelectionMS__pb2.rankedProxResponse.FromString,
                _registered_method=True)
        self.getDrive = channel.unary_unary(
                '/proxPackage.siteSelectionMS/getDrive',
                request_serializer=protos_dot_siteSelectionMS__pb2.rankProxRequest.SerializeToString,
                response_deserializer=protos_dot_siteSelectionMS__pb2.rankedProxResponse.FromString,
                _registered_method=True)
        self.getCommDrive = channel.unary_unary(
                '/proxPackage.siteSelectionMS/getCommDrive',
                request_serializer=protos_dot_siteSelectionMS__pb2.rankProxRequest.SerializeToString,
                response_deserializer=protos_dot_siteSelectionMS__pb2.rankedProxResponse.FromString,
                _registered_method=True)


class siteSelectionMSServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getCommute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getDrive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCommDrive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_siteSelectionMSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getCommute': grpc.unary_unary_rpc_method_handler(
                    servicer.getCommute,
                    request_deserializer=protos_dot_siteSelectionMS__pb2.rankProxRequest.FromString,
                    response_serializer=protos_dot_siteSelectionMS__pb2.rankedProxResponse.SerializeToString,
            ),
            'getDrive': grpc.unary_unary_rpc_method_handler(
                    servicer.getDrive,
                    request_deserializer=protos_dot_siteSelectionMS__pb2.rankProxRequest.FromString,
                    response_serializer=protos_dot_siteSelectionMS__pb2.rankedProxResponse.SerializeToString,
            ),
            'getCommDrive': grpc.unary_unary_rpc_method_handler(
                    servicer.getCommDrive,
                    request_deserializer=protos_dot_siteSelectionMS__pb2.rankProxRequest.FromString,
                    response_serializer=protos_dot_siteSelectionMS__pb2.rankedProxResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proxPackage.siteSelectionMS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proxPackage.siteSelectionMS', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class siteSelectionMS(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getCommute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proxPackage.siteSelectionMS/getCommute',
            protos_dot_siteSelectionMS__pb2.rankProxRequest.SerializeToString,
            protos_dot_siteSelectionMS__pb2.rankedProxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getDrive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proxPackage.siteSelectionMS/getDrive',
            protos_dot_siteSelectionMS__pb2.rankProxRequest.SerializeToString,
            protos_dot_siteSelectionMS__pb2.rankedProxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCommDrive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proxPackage.siteSelectionMS/getCommDrive',
            protos_dot_siteSelectionMS__pb2.rankProxRequest.SerializeToString,
            protos_dot_siteSelectionMS__pb2.rankedProxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
