# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/siteSelectionMS.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/siteSelectionMS.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprotos/siteSelectionMS.proto\x12\x0bproxPackage\"%\n\x0frankProxRequest\x12\x12\n\nrankPlease\x18\x01 \x01(\t\"S\n\x12rankedProxResponse\x12\x13\n\x0brankedAreas\x18\x01 \x01(\t\x12\x10\n\x08rankings\x18\x02 \x01(\x02\x12\x16\n\x0erankedResponse\x18\x03 \x01(\t2\xfe\x01\n\x0fsiteSelectionMS\x12M\n\ngetCommute\x12\x1c.proxPackage.rankProxRequest\x1a\x1f.proxPackage.rankedProxResponse\"\x00\x12K\n\x08getDrive\x12\x1c.proxPackage.rankProxRequest\x1a\x1f.proxPackage.rankedProxResponse\"\x00\x12O\n\x0cgetCommDrive\x12\x1c.proxPackage.rankProxRequest\x1a\x1f.proxPackage.rankedProxResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.siteSelectionMS_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RANKPROXREQUEST']._serialized_start=45
  _globals['_RANKPROXREQUEST']._serialized_end=82
  _globals['_RANKEDPROXRESPONSE']._serialized_start=84
  _globals['_RANKEDPROXRESPONSE']._serialized_end=167
  _globals['_SITESELECTIONMS']._serialized_start=170
  _globals['_SITESELECTIONMS']._serialized_end=424
# @@protoc_insertion_point(module_scope)
