"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class rankProxRequest(google.protobuf.message.Message):
    """The request message containing the request."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RANKPLEASE_FIELD_NUMBER: builtins.int
    rankPlease: builtins.str
    def __init__(
        self,
        *,
        rankPlease: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["rankPlease", b"rankPlease"]) -> None: ...

global___rankProxRequest = rankProxRequest

@typing.final
class rankedProxResponse(google.protobuf.message.Message):
    """The response message containing the area."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RANKEDAREAS_FIELD_NUMBER: builtins.int
    RANKINGS_FIELD_NUMBER: builtins.int
    RANKEDRESPONSE_FIELD_NUMBER: builtins.int
    rankedAreas: builtins.str
    rankings: builtins.float
    rankedResponse: builtins.str
    def __init__(
        self,
        *,
        rankedAreas: builtins.str = ...,
        rankings: builtins.float = ...,
        rankedResponse: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["rankedAreas", b"rankedAreas", "rankedResponse", b"rankedResponse", "rankings", b"rankings"]) -> None: ...

global___rankedProxResponse = rankedProxResponse
